### ISSUE TITLE
[Feature]: 2024年版データベースの新規作成

### ISSUE THREAD

**Issue by serima** [magic-spreadsheets/magic-spreadsheets#41]
### リクエストの内容

そろそろ、26卒を対象としたサマーインターン等の募集が始まりつつあるため、2024年版のデータベースを新規作成してもよいかと思いました。

- [Google ソフトウェア エンジニアリング インターン、2024 年夏季](https://www.google.com/about/careers/applications/u/0/jobs/results/78352561104396998-2024)

時期的にはまだ対象となるプログラムも少ないのでしばらくは2023年版もトップページのわかりやすいところに併記しておいたほうが良いかもしれません。
（最下部のバックナンバーから辿れるから問題ないという意見もありそうですが）

### Todo

- [ ] 2024年版DBの新規作成
- [ ] トップページへリンクを張る

**Comment by keigomichi** [comment]
Issueありがとうございます 🙇 
ちょうど、引き継ぎに向けた準備を進めているところでした！

近々公開できるかと思いますので、少々お待ちください 🙏
